### ISSUE TITLE
Errors are Ambiguous

### ISSUE THREAD

**Issue by kjeffrisps** [ncw/stressdisk#12]
I am using your program to validate solid state drives, but the error outputs do not make any sense.  There is no description of what the errors actually are (1 bit wrong, 1 byte wrong, etc.).  I am also seeing an abnormally high number of errors.  Here is an example of the results of running the "cycle" run on an enterprise-grade intel SSD drive (240 GB) for 24 hours.

Read: 20,775,224 MByte (488.23 MByte/s)
Write: 10,506,396 MByte (240.3 MByte/s)
Errors: 75,202,464 

I have also attached a log file for your reference.

[stressdisk_enterprise_1.log](https://github.com/ncw/stressdisk/files/3009651/stressdisk_enterprise_1.log)

**Comment by ncw** [comment]
The error lines look like this

    2019/03/07 10:55:09 0AA00000: 2D, A1 diff 8C

They are `address`, `file1 value`, `file 2 value` and the diff which is `file1_value XOR file2_value`.  This will be a binary number for a single bit error so 01, 02, 04, 08, 10, 20, 40, 80.

The diffs in your log look pretty random. It looks like `TST_0000` got corrupted when it was written to the disk as the errors are consistent.

The actual errors aren't that important though, you shouldn't get **any** - if you do then
- run memtest86 on the machine for 48 hours to check for RAM problems, if this passes then
- try the stressdisk test on another machine if you can, if this fails then
- discard or return the media

**Comment by kjeffrisps** [comment]
Thanks for the help, I will run this test and update you on whether or not that was the issue.  Thanks for creating such a great tool!

**Comment by ncw** [comment]
> Thanks for the help, I will run this test and update you on whether or not that was the issue.

Great

> Thanks for creating such a great tool!

You are welcome :-)

I put a version of the above text in the README

**Comment by kjeffrisps** [comment]
I ran MemTest86 (couldn't run plus because the computer is UEFI boot), and strangely enough it finished all four passes with 0 errors.  I'll try it on another machine.
