### ISSUE TITLE
Make a C++ version

### ISSUE THREAD

**Issue by Zero3K** [ncw/stressdisk#17]
It would be nice if you or someone else could do that so that way a developer that I am having work on a UDFS driver can figure out how it works so he can change it to where it causes the read errors for both of us instead of just me.

**Comment by ncw** [comment]
Go will seem mostly familiar to a C programmer apart from the type definitions being back to front so I'd encourage your developer to look at the stressdisk source code if needed.

It is out of scope for this project to make a C++ version, though If someone wants to port to C++ the MIT license allows that and it would be fine with me.
