### ISSUE TITLE
Problem on Mac OS 10.6.8 with new drive

### ISSUE THREAD

**Issue by sfenwick** [ncw/stressdisk#4]
First time user of stressdisk, so not sure where the issue is with this:

Mac Pro (2010), Mac OS 10.6.8
New WD Black 4TB in external eSATA dock. Dock has a fan and drive is room temp to the touch.

I started stressdisk yesterday with the command:

`./stressdisk -duration=24h0m0s -logfile="stressdisk.log" run /Volumes/NewDisk/`

I was writing fine, about 175MB/s:

`2015/04/11 14:19:54 Writing file "/Volumes/NewDisk/TST_0024" size 1000000000`
`2015/04/11 14:20:00 Writing file "/Volumes/NewDisk/TST_0025" size 1000000000`
`2015/04/11 14:20:05 Writing file "/Volumes/NewDisk/TST_0026" size 1000000000`
`2015/04/11 14:20:11 Writing file "/Volumes/NewDisk/TST_0027" size 1000000000`
`2015/04/11 14:20:16 Writing file "/Volumes/NewDisk/TST_0028" size 1000000000`

As it tried to fill the disk, it slowed way, way down:
`2015/04/12 03:13:40 Writing file "/Volumes/NewDisk/TST_3989" size 1000000000`
`2015/04/12 03:13:56 Writing file "/Volumes/NewDisk/TST_3990" size 1000000000`
`2015/04/12 08:48:03 Writing file "/Volumes/NewDisk/TST_3991" size 1000000000`
`2015/04/12 10:52:18 Writing file "/Volumes/NewDisk/TST_3992" size 1000000000`
`2015/04/12 12:03:40 Writing file "/Volumes/NewDisk/TST_3993" size 1000000000`
`2015/04/12 13:14:52 Writing file "/Volumes/NewDisk/TST_3994" size 1000000000`
`2015/04/12 14:26:27 Writing file "/Volumes/NewDisk/TST_3995" size 1000000000`

We're past the 24 hours (started 4/11 14:17:42, currently 14:50:45) and it's now reading at about 25MB/s, which I assume is the read random portion of the test. Since it finished writing after the timer should have expired, will it ever stop? Also, are any error messages flushed out of whatever stream they are written to, so that if there are no errors visible I can assume that there have been none?

I'll let it continue to run for now. If I recall, if I kill it now and restart it, will it detect the disk as full and just read the existing files?

**Comment by ncw** [comment]
As the disk becomes full it will have to write fragmented files most likely, so it isn't entirely unexpected it slows down. This might be caused by something else - maybe seeking back to the catalogue - I'm not sure.

The `-duration` flag only refers to the read portion of the test, so it should stop 24 hours after it finished writing the test files.

Any errors are summarised in the stats which are printed every minute and they will be printed at the end of the run too.

And yes, if you stop the process, it will detect the disks as full and carry on.

**Comment by ncw** [comment]
How did the test go?

**Comment by ncw** [comment]
I'm going to close this I haven't heard from you in a while.  If you have more info then please re-open.

Thanks

Nick
