### ISSUE TITLE
Any particular reason to use this app over badblocks on linux?

### ISSUE THREAD

**Issue by mafrosis** [ncw/stressdisk#7]
Thanks for building!

**Comment by mafrosis** [comment]
I should read the README in full first

**Comment by ncw** [comment]
This app tries a lot harder to find bad stuff than badblocks and will write data to the filesystem to find it.

**Comment by grahamperrin** [comment]
https://linux.die.net/man/8/badblocks `badblocks(8)` can test the entirety of a disk – without overwriting user data, if run with care. 

`stressdisk` can  test the free space within a file system, so it's best suited to an empty file system that occupies as much as possible of the device.

**Comment by daboross** [comment]
@grahamperrin I think there is the significant advantage of stressdisk being a _stress_ tool as well, though. It doesn't just test each block with different patterns, it specifically tries to overload the kernel & usb device, so if any bugs show up under extreme pressure, they become apparent.

badblocks simply tests each block with different patterns. That picks up if any segment of the drive is _always broken_, but won't pick up anything that only appears under stress.

**Comment by grahamperrin** [comment]
Thanks for the additional explanation. 

I think it will be useful to mention kernel overload (or words to that effect) under https://github.com/ncw/stressdisk#stressdisk

**Comment by ncw** [comment]
@grahamperrin if you'd like to suggest a fix, click the pencil icon on the top right and send a suggestion :-)
